using OpenWiiManager.Checking;
using OpenWiiManager.Language.Attributes;
using OpenWiiManager.Language.Extensions;
using OpenWiiManager.Tools;
using System.Reflection;
using System.Xml.Linq;

namespace OpenWiiManager
{
    public static class ApplicationState
    {
        const int STATE_FORMAT = 1;

        [StateSerialization]
        private static DateTimeOffset lastFeedUpdate;

        [StateSerialization]
        private static Point mainWindowPos;

        [StateSerialization]
        private static Size mainWindowSize;

        [StateSerialization]
        private static int mainWindowSplitDistance;

        public static DateTimeOffset LastFeedUpdate { get => lastFeedUpdate; set { lastFeedUpdate = value; Serialize(); } }
        public static Point MainWindowPos { get => mainWindowPos; set { mainWindowPos = value; Serialize(); } }
        public static Size MainWindowSize { get => mainWindowSize; set { mainWindowSize = value; Serialize(); } }
        public static int MainWindowSplitDistance { get => mainWindowSplitDistance; set { mainWindowSplitDistance = value; Serialize(); } }

        private static void Serialize()
        {
            var doc = new XDocument(
                new XText(Environment.NewLine),
                new XComment("THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE MANUALLY!"),
                new XText(Environment.NewLine),
                new XElement("state", new XAttribute("format", STATE_FORMAT),
                    GetSerializableFields()
                        .Select(f => new XElement(
                            f.Name,
                            f.GetValue(null).SerializeToXmlNode()
                        ))
                )
            );

            IOUtil.EnsureDirectoryExists(ApplicationEnviornment.LocalUserDataDirectory);

            doc.SaveWithoutFormatting(ApplicationEnviornment.StateFilePath);
        }

        private static IEnumerable<FieldInfo> GetSerializableFields()
        {
            return typeof(ApplicationState)
                .GetFields(BindingFlags.Static | BindingFlags.NonPublic)
                .Where(f => f.GetCustomAttribute<StateSerializationAttribute>() != null);
        }

        private static void Deserialize()
        {
            if (!File.Exists(ApplicationEnviornment.StateFilePath))
                return;

            var doc = XDocument.Load(ApplicationEnviornment.StateFilePath);
            RuntimeAssertions.True(doc.Root?.Name == "state", $"Wrong root tag. Got {doc.Root?.Name ?? "<NULL>"}");
            RuntimeAssertions.True(doc.Root?.Attribute("format")?.Value == STATE_FORMAT.ToString(), "Wrong format version");

            var fields = GetSerializableFields();
            foreach (var field in fields)
            {
                var name = field.Name;
                var element = doc.Root?.Element(name);
                if (element == null) continue;
                var child = element.Descendants().FirstOrDefault();
                if (child == null) continue;
                try
                {
                    var value = SerializationUtil.DeserializeFromXmlNode(field.FieldType, child);
                    field.SetValue(null, value);
                }
                catch (TypeInitializationException) { }
                catch (InvalidOperationException) { }
            }
        }

        static ApplicationState()
        {
            Deserialize();
        }
    }
}